/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.Product;
import Business.Network.Network;
import Business.OperationProcedure.OperationProcedure;
import Business.Organization.CareTeamOrganization;
import Business.Organization.DeviceManagerOrganization;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.OperationRequestToCareTeamWorkRequest;
import Business.WorkQueue.OperationRequestToDeviceManagerWorkRequest;
import Business.WorkQueue.WorkRequest;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shubham
 */
public class RequestOperationJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    // private Enterprise enterprise;
    private HospitalEnterprise hospitalEnterprise;
    private UserAccount userAccount;
    private DoctorOrganization docOrganization;
    private EcoSystem system;
    OperationRequestToCareTeamWorkRequest request;
    OperationRequestToDeviceManagerWorkRequest req;

    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestOperationJPanel(JPanel userProcessContainer, UserAccount account, DoctorOrganization docOrganization, EcoSystem system, HospitalEnterprise hospitalEnterprise) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.docOrganization = docOrganization;
        this.userAccount = account;
        this.system = system;
        this.hospitalEnterprise = hospitalEnterprise;
        populateTable();
        populateDeviceTable();

    }
    
    private void populateDeviceTable(){
        
        DefaultTableModel dtm = (DefaultTableModel) tblDevice.getModel();

        dtm.setRowCount(0);

        for (WorkRequest a : userAccount.getWorkQueue().getWorkRequestList()) {
            if (a instanceof OperationRequestToDeviceManagerWorkRequest) {

                Object[] row = new Object[4];

                row[0] = a;
               // row[1] = r.getSender();
                row[1] = ((OperationRequestToDeviceManagerWorkRequest)a).getDevicetype();
                row[2] = ((OperationRequestToDeviceManagerWorkRequest)a).getOperationDate();
                row[3] = a.getStatus();
                //row[4]=((OperationRequestToCareTeamWorkRequest)r).getCareTeamMembers();
                dtm.addRow(row);
            }

        }
    
      }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblOperation.getModel();

        model.setRowCount(0);

        for (WorkRequest r : userAccount.getWorkQueue().getWorkRequestList()) {
            if (r instanceof OperationRequestToCareTeamWorkRequest) {

                Object[] row = new Object[5];

                row[0] = r;
               // row[1] = r.getSender();
                row[1] = r.getReceiver();
                row[2] = r.getStatus();
                row[3] = r.getOperatingRoom();
                row[4]=((OperationRequestToCareTeamWorkRequest)r).getCareTeamMembers();
                model.addRow(row);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbOperation = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbOperationDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        cmbDeviceType = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOperation = new javax.swing.JTable();
        refreshJButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCareTeam = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDevice = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        requestTestJButton.setText("Request Approval");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Message");

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Operation Type");

        cmbOperation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Heart Surgey", "Hip Replacement", "Sping Surgery", "Kidney Transplant", " " }));
        cmbOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOperationActionPerformed(evt);
            }
        });

        jLabel4.setText("Date of Operation");

        jLabel2.setText("Device Type");

        cmbDeviceType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "evel 1", "level 2", "level 3", "level 4" }));

        tblOperation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Message", "Receiver", "Status", "Operating Room", "No. Of  CareTeam Members"
            }
        ));
        jScrollPane1.setViewportView(tblOperation);

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("No. Of CareTeam Members");

        tblDevice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Device Type", "Date of Operation", "Status"
            }
        ));
        jScrollPane2.setViewportView(tblDevice);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(jLabel3)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(backJButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel2)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbDeviceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbOperationDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(messageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCareTeam)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(requestTestJButton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshJButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbOperationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(messageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(cmbDeviceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(cmbOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addComponent(jLabel4))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCareTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(requestTestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(backJButton)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        String message = messageJTextField.getText();
        OperationProcedure procedure = new OperationProcedure();
        Product product = new Product();

        request = new OperationRequestToCareTeamWorkRequest();
        //request.setSupplier((Supplier)userAccount.getEmployee());
        request.setMessage(message);
        request.setSender(userAccount);
        request.setStatus("Sent");
        request.setDocOrganization(docOrganization);
        request.setOperatingProcedure(procedure);
        request.setDoctorName(userAccount.getEmployee().getName());
        request.setOperationDate(cmbOperationDate.getDate());
        request.setOperationType(String.valueOf(cmbOperation.getSelectedItem()));
        request.setCareTeamMembers(Integer.parseInt(txtCareTeam.getText()));

       // userAccount.getWorkQueue().getWorkRequestList().add(request);
        //request.getSupplier().setEnrolementStatus("Request Sent");

        Organization org = null;
        for (Organization organization : hospitalEnterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof CareTeamOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        if (message == null) {
            JOptionPane.showMessageDialog(null, "Please Enter A Message");
        }

        req = new OperationRequestToDeviceManagerWorkRequest();
        //request.setSupplier((Supplier)userAccount.getEmployee());
        req.setMessage(message);
        req.setSender(userAccount);
        req.setStatus("Sent");
        req.setDocOrganization(docOrganization);
        req.setOperatingProcedure(procedure);
        req.getOperatingProcedure().setProduct(product);
        req.setDevicetype(String.valueOf(cmbOperation.getSelectedItem()));
        req.setOperationDate(cmbOperationDate.getDate());
        //req.setDeviceName(txtDeviceName.getText());
       // req.setDevicetype(String.valueOf(cmbDeviceType.getSelectedItem()));
       // userAccount.getWorkQueue().getWorkRequestList().add(req);
        
         
        for (Organization organization : hospitalEnterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof DeviceManagerOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(req);
            userAccount.getWorkQueue().getWorkRequestList().add(req);
        }
        if (message == null) {
            JOptionPane.showMessageDialog(null, "Please Enter A Message");
        }



    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
        populateDeviceTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void cmbOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOperationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOperationActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox cmbDeviceType;
    private javax.swing.JComboBox cmbOperation;
    private com.toedter.calendar.JDateChooser cmbOperationDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTable tblDevice;
    private javax.swing.JTable tblOperation;
    private javax.swing.JTextField txtCareTeam;
    // End of variables declaration//GEN-END:variables
}
